import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";

export default function Home() {
  if (typeof window !== "undefined") {
    localStorage.setItem(
      "token",
      "90042c18ba8d8c0c5a2f1385681d99eac5b55a153c7c3eb08f7e29566e5ba545"
    );
  } else {
    console.log("ndak bisa");
  }
  const config = {
    headers: { Authorization: `Bearer ${localStorage.getItem("token")}` },
  };
  return (
    <div className="container justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center">
        <h2 className="text-green-400">{}</h2>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
